"""Interactive helper: open a MuJoCo scene, adjust the camera by hand and print its pose
(pos / xyaxes / quat) so it can be pasted into the scene XML or randomize_scene.py's config."""
import mujoco
import mujoco.viewer
import numpy as np
from scipy.spatial.transform import Rotation as R

import argparse
from pathlib import Path

# Repository root (classifier/mujoco/ -> repo) and git-ignored data directory.
REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "data"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--model_path", type=str,
                    default=str(DATA_DIR / "classifier" / "mujoco" / "random_cluttered_scene.xml"),
                    help="MuJoCo XML to open (default: last scene generated by randomize_scene.py)")
args = parser.parse_args()

# Load your MuJoCo model
MODEL_PATH = args.model_path
model = mujoco.MjModel.from_xml_path(MODEL_PATH)
data = mujoco.MjData(model)

# Start viewer
with mujoco.viewer.launch_passive(model, data) as viewer:
    print("Adjust the camera manually in the viewer.")
    input("Press Enter when you're done...")

    # Access internal camera struct
    cam = viewer.cam
    cam_id = cam.fixedcamid

    # Get camera pos and xyaxes
    pos = model.cam_pos[cam_id]
    mat = model.cam_mat[cam_id].reshape(3, 3)

    # Get xyaxes (first 2 columns of rotation matrix)
    xyaxes = mat[:, :2].flatten()
    xyaxes_str = " ".join(f"{v:.6f}" for v in xyaxes)
    pos_str = " ".join(f"{p:.6f}" for p in pos)

    # Full rotation matrix to quaternion
    rot = R.from_matrix(mat)
    quat = rot.as_quat()  # [x, y, z, w]
    quat_str = f"{quat[3]:.6f} {quat[0]:.6f} {quat[1]:.6f} {quat[2]:.6f}"  # reorder to w x y z for MuJoCo

    # Output
    print("\n=== Camera Pose ===")
    print(f'pos="{pos_str}"')
    print(f'xyaxes="{xyaxes_str}"')
    print(f'quat="{quat_str}"')
